import { Event } from "./types";

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Vivid Sydney Light Festival",
    date: "2026-05-22",
    time: "18:00",
    venue: "Sydney Opera House",
    address: "Bennelong Point, Sydney NSW 2000",
    city: "Sydney",
    description: "Experience the world's largest festival of light, music, and ideas. Vivid Sydney transforms the city into a canvas of light art, projections, and installations.",
    category: "Festival",
    tags: ["lights", "art", "music", "outdoor"],
    imageUrl: "https://images.unsplash.com/photo-1524293581917-878a6d017c71?w=600&h=400&fit=crop",
    sourceWebsite: "vividsydney.com",
    originalUrl: "https://www.vividsydney.com",
    lastScraped: "2026-02-27T10:00:00Z",
    status: "new",
  },
  {
    id: "2",
    title: "Sydney Comedy Festival Gala",
    date: "2026-04-15",
    time: "19:30",
    venue: "Enmore Theatre",
    address: "118-132 Enmore Rd, Newtown NSW 2042",
    city: "Sydney",
    description: "A hilarious night featuring Australia's best comedians and international acts. The opening gala kicks off weeks of laughs across the city.",
    category: "Comedy",
    tags: ["comedy", "live", "entertainment"],
    imageUrl: "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=600&h=400&fit=crop",
    sourceWebsite: "sydneycomedyfest.com.au",
    originalUrl: "https://www.sydneycomedyfest.com.au",
    lastScraped: "2026-02-26T14:30:00Z",
    status: "new",
  },
  {
    id: "3",
    title: "Bondi to Coogee Coastal Run",
    date: "2026-06-14",
    time: "07:00",
    venue: "Bondi Beach",
    address: "Queen Elizabeth Dr, Bondi Beach NSW 2026",
    city: "Sydney",
    description: "Join thousands of runners on the iconic Bondi to Coogee coastal path. 6km of stunning ocean views, cliff-top trails, and beachside vibes.",
    category: "Sports",
    tags: ["running", "fitness", "outdoor", "beach"],
    imageUrl: "https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=600&h=400&fit=crop",
    sourceWebsite: "bondicoastalrun.com.au",
    originalUrl: "https://www.bondicoastalrun.com.au",
    lastScraped: "2026-02-27T08:15:00Z",
    status: "updated",
  },
  {
    id: "4",
    title: "Night Noodle Markets",
    date: "2026-10-10",
    time: "17:00",
    venue: "Hyde Park",
    address: "Elizabeth St, Sydney NSW 2000",
    city: "Sydney",
    description: "Sydney's favourite outdoor food festival returns with over 30 Asian-inspired hawker stalls, live entertainment, and lantern installations.",
    category: "Food & Drink",
    tags: ["food", "night market", "asian cuisine", "outdoor"],
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop",
    sourceWebsite: "goodfoodmonth.com",
    originalUrl: "https://www.goodfoodmonth.com",
    lastScraped: "2026-02-25T16:00:00Z",
    status: "new",
  },
  {
    id: "5",
    title: "Art Gallery of NSW: Modern Horizons",
    date: "2026-03-20",
    time: "10:00",
    venue: "Art Gallery of New South Wales",
    address: "Art Gallery Rd, Sydney NSW 2000",
    city: "Sydney",
    description: "A landmark exhibition exploring contemporary Australian art through immersive installations, paintings, and digital works by 40+ artists.",
    category: "Art",
    tags: ["art", "exhibition", "gallery", "contemporary"],
    imageUrl: "https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=600&h=400&fit=crop",
    sourceWebsite: "artgallery.nsw.gov.au",
    originalUrl: "https://www.artgallery.nsw.gov.au",
    lastScraped: "2026-02-27T09:00:00Z",
    status: "updated",
  },
  {
    id: "6",
    title: "Sydney Tech Connect Meetup",
    date: "2026-03-28",
    time: "18:30",
    venue: "Atlassian Central",
    address: "8 Central Ave, Eveleigh NSW 2015",
    city: "Sydney",
    description: "Monthly meetup for developers, designers, and startup founders. This month: AI in Production — talks, networking, pizza, and drinks.",
    category: "Tech",
    tags: ["technology", "meetup", "networking", "AI"],
    imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&h=400&fit=crop",
    sourceWebsite: "meetup.com",
    originalUrl: "https://www.meetup.com/sydney-tech",
    lastScraped: "2026-02-27T11:00:00Z",
    status: "new",
  },
  {
    id: "7",
    title: "Sunset Symphony at the Harbour",
    date: "2026-04-05",
    time: "17:30",
    venue: "Mrs Macquaries Point",
    address: "Mrs Macquaries Rd, Sydney NSW 2000",
    city: "Sydney",
    description: "The Sydney Symphony Orchestra performs a free outdoor concert as the sun sets over the harbour. Bring a picnic and enjoy world-class music.",
    category: "Music",
    tags: ["classical", "orchestra", "outdoor", "free"],
    imageUrl: "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=600&h=400&fit=crop",
    sourceWebsite: "sydneysymphony.com",
    originalUrl: "https://www.sydneysymphony.com",
    lastScraped: "2026-02-26T20:00:00Z",
    status: "new",
  },
  {
    id: "8",
    title: "Paddington Markets",
    date: "2026-03-07",
    time: "10:00",
    venue: "Paddington Uniting Church",
    address: "395 Oxford St, Paddington NSW 2021",
    city: "Sydney",
    description: "Browse 150+ stalls of handmade fashion, jewellery, art, and gourmet food at Sydney's iconic Saturday market. Running since 1973.",
    category: "Markets",
    tags: ["markets", "handmade", "fashion", "food"],
    imageUrl: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&h=400&fit=crop",
    sourceWebsite: "paddingtonmarkets.com.au",
    originalUrl: "https://www.paddingtonmarkets.com.au",
    lastScraped: "2026-02-27T07:00:00Z",
    status: "inactive",
  },
  {
    id: "9",
    title: "Sydney Harbour Kayak Tour",
    date: "2026-04-12",
    time: "06:30",
    venue: "Lavender Bay",
    address: "Lavender Bay, North Sydney NSW 2060",
    city: "Sydney",
    description: "Paddle past the Opera House and under the Harbour Bridge at sunrise. A guided 2-hour kayak experience with stunning city skyline views.",
    category: "Adventure",
    tags: ["kayak", "harbour", "outdoor", "sunrise"],
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&h=400&fit=crop",
    sourceWebsite: "sydneyharbourkayaks.com.au",
    originalUrl: "https://www.sydneyharbourkayaks.com.au",
    lastScraped: "2026-02-26T18:00:00Z",
    status: "new",
  },
  {
    id: "10",
    title: "Tropfest Short Film Festival",
    date: "2026-02-14",
    time: "16:00",
    venue: "Centennial Park",
    address: "Grand Dr, Centennial Park NSW 2021",
    city: "Sydney",
    description: "The world's largest short film festival screens the top 16 finalist films outdoors under the stars. Free entry, BYO picnic.",
    category: "Film",
    tags: ["film", "festival", "outdoor", "free"],
    imageUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&h=400&fit=crop",
    sourceWebsite: "tropfest.com",
    originalUrl: "https://www.tropfest.com",
    lastScraped: "2026-02-10T12:00:00Z",
    status: "inactive",
  },
  {
    id: "11",
    title: "Sculpture by the Sea",
    date: "2026-10-22",
    time: "09:00",
    venue: "Bondi to Tamarama Coastal Walk",
    address: "Marks Park, Tamarama NSW 2026",
    city: "Sydney",
    description: "The world's largest free-to-the-public outdoor sculpture exhibition featuring 100+ sculptures along the breathtaking Bondi coastline.",
    category: "Art",
    tags: ["sculpture", "outdoor", "free", "coastal"],
    imageUrl: "https://images.unsplash.com/photo-1561839561-b13bcfe95249?w=600&h=400&fit=crop",
    sourceWebsite: "sculpturebythesea.com",
    originalUrl: "https://www.sculpturebythesea.com",
    lastScraped: "2026-02-27T06:30:00Z",
    status: "new",
  },
  {
    id: "12",
    title: "Sydney Wine & Cheese Festival",
    date: "2026-05-03",
    time: "12:00",
    venue: "The Rocks",
    address: "George St, The Rocks NSW 2000",
    city: "Sydney",
    description: "Sample over 200 wines from Australian vineyards paired with artisan cheeses. Live jazz, masterclasses, and harbour views included.",
    category: "Food & Drink",
    tags: ["wine", "cheese", "tasting", "jazz"],
    imageUrl: "https://images.unsplash.com/photo-1474722883778-792e7990302f?w=600&h=400&fit=crop",
    sourceWebsite: "sydneywinefest.com.au",
    originalUrl: "https://www.sydneywinefest.com.au",
    lastScraped: "2026-02-26T22:00:00Z",
    status: "updated",
  },
];

export const categories = [
  "All",
  "Festival",
  "Comedy",
  "Sports",
  "Food & Drink",
  "Art",
  "Tech",
  "Music",
  "Markets",
  "Adventure",
  "Film",
];
